apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsecurebuckets.fintech.io
spec:
  group: fintech.io
  names:
    kind: XSecureBucket
    plural: xsecurebuckets
  claimNames:
    kind: SecureBucket
    plural: securebuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                required:
                - region
