apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: trading-service-pod-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: trading-service
  scheduler:
    cron: "@every 10m"
